# Database settings.
database:
    # the lastName of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: akshayraj
    # the password
    password: Har3krishna
    # the JDBC URL; the database is called sophist
    url: jdbc:mysql://localhost:3306/sophist